version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.4-node-browsers
    - image: circleci/mysql:8.0.20-ram
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_USER: forge
        MYSQL_DATABASE: forge
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_PASSWORD: forge
    steps:
    - checkout
    - run: sudo apt update
    - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
    - run: sudo docker-php-ext-install zip bcmath pdo_mysql
    - run: sudo apt-get install default-mysql-client
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: v1-dependencies-{{ checksum "composer.json" }}
        paths:
        - ./vendor
    - restore_cache:
        keys:
        - node-v1-{{ checksum "package.json" }}
        - node-v1-
    - run: yarn install
    - save_cache:
        key: node-v1-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: Generate App key
        command: php artisan key:generate
    - run: touch storage/testing.sqlite
    - run: php artisan config:clear
    - run: mysqladmin create laravel --host="127.0.0.1" --user="root" --password=""
    - run: php artisan migrate --env=local --database=mysql --force
    - run: ./vendor/bin/phpunit
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/reidsneo/maes-saas/compare/00e90f5c32cb12dfdd0f22cc1045e027c5b0e645...aae8807a3e10d89ccc2b3fab5a503fcffd6afa69
  deploy:
    machine:
      enabled: true
    working_directory: ~/laravel
    steps:
    - checkout
   # - run:
   #     name: run deployment script
   #     command: ./bin/deployment-script.sh
    - add_ssh_keys:
        fingerprints:
        - c2:f2:cc:a6:0d:5e:03:8a:81:3f:0c:44:36:cd:82:bf
    - run:
        name: fix host authenticity for production server
        command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - run:
        name: deploy app
        command: scp laravel $SSH_USERNAME@$SSH_HOST:/var/www/html/
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/reidsneo/maes-saas/compare/00e90f5c32cb12dfdd0f22cc1045e027c5b0e645...aae8807a3e10d89ccc2b3fab5a503fcffd6afa69
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - deploy
